<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paciente [
<!-- DTD definido dentro del xml -->
   <!-- Definicion de la informacion del paciente -->
   <!ELEMENT paciente (nombre,edad,examen)>
      <!-- Definicion de los campos de paciente -->
      <!ELEMENT nombre (#PCDATA)>
      <!ELEMENT edad (#PCDATA)>
      <!-- Definicion de los examens -->
      <!ELEMENT examen (codigo,descripcion,resultado)>
         <!-- Definicion de los campos del examen -->
         <!ELEMENT codigo (#PCDATA)>
         <!ELEMENT descripcion (#PCDATA)>
         <!-- Definicion de los resultados -->
         <!ELEMENT resultado (valor_minimo,valor_maximo,valor,analisis)>
            <!-- Definicion de los campos de resultado -->
            <!ELEMENT valor_minimo (#PCDATA)>
            <!ELEMENT valor_maximo (#PCDATA)>
            <!ELEMENT valor (#PCDATA)>
            <!ATTLIST valor unidad CDATA #FIXED "mlgr">
            <!ELEMENT analisis (#PCDATA)>
]>
<paciente>
   <nombre>Duckman</nombre>
   <edad>40</edad>
   <examen>
      <codigo>C041</codigo>
      <descripcion>Serologia</descripcion>
      <resultado>
         <valor_minimo>1.0</valor_minimo>
         <valor_maximo/>
         <valor>5.0</valor>
         <analisis/>
      </resultado>
   </examen>
</paciente>
