=== jfcmacro/wb-jfcmacro-java/xml/valido/group.dtd
<!ELEMENT grupo (nombre,url,miembro,miembro?,(mainclasses|haskellexecs)*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT miembro (nombre,codigo,email)>
<!ELEMENT mainclasses ((mainclass)+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT mainclass (EMPTY)>
<!ELEMENT haskellexecs (cabalfile,haskellexec)>
<!ELEMENT cabalfile (EMPTY)>
<!ELEMENT haskellexec (EMPTY)>
<!ATTLIST mainclass classpath CDATA ".">
<!ATTLIST mainclass package   CDATA ".">
<!ATTLIST mainclass clase     CDATA #REQUIRED>
<!ATTLIST cabalfile cabal CDATA #REQUIRED>
<!ATTLIST haskellexec name CDATA #REQUIRED>
<!ATTLIST haskellexec path CDATA "">

=== jfcmacro/wb-jfcmacro-java/xml/valido/group2.xml
<?xml version="1.1" encoding="utf-8"?>
<!DOCTYPE group SYSTEM "http://www1.eafit.edu.co/fcardona/cursos/st0270/group.dtd">
<grupo>
   <nombre>oberonmenoszero</nombre>
   <url>https://subversion.assembla.com/svn/oberomenoszero/trunk</url>
   <miembro>
      <nombre>Juan Francisco Cardona McCormick</nombre>
      <codigo>198610250010</codigo>
      <email>fcardona@eafit.edu.co</email>
   </miembro>
   <miembro>
      <nombre>Alejandro Gómez Londoño</nombre>
      <codigo>201010001010</codigo>
      <email>alegomez544@eafit.edu.co</email>
   </miembro>
   <mainclases>
     <mainclass classpath="bin/classes" clase="MainoberomenoszeroLexer"/>
   </mainclases>
</grupo>

=== jfcmacro/wb-jfcmacro-java/xml/valido/group1.xml
<?xml version="1.1" encoding="utf-8" ?>
<!DOCTYPE grupo SYSTEM "group.dtd">
<grupo>
   <nombre>Principal</nombre>
   <url>https://subversion.assembla.com/svn/oberomenoszero/trunk</url>
   <miembro>
      <nombre>Juan Francisco Cardona McCormick</nombre>
      <codigo>198610250010</codigo>
      <email>fcardona@eafit.edu.co</email>
   </miembro>
   <miembro>
      <nombre>Alejandro Gómez Londoño</nombre>
      <codigo>201010001010</codigo>
      <email>alegomez544@eafit.edu.co</email>
   </miembro>
   <haskellexecs>
      <cabalfile cabal="oberomenoszero.cabal"/>
      <haskellexec name="MoberomenoszeroLexer"/>
   </haskellexecs>
</grupo>
