=== jfcmacro/wb-jfcmacro-java/xml/expr/expr.dtd
<!ELEMENT expr   (add 
                 | sub 
                 | mul 
                 | div 
                 | number 
                 | id)>
<!ELEMENT add    (expr,expr)>
<!ELEMENT sub    (expr,expr)>
<!ELEMENT mul    (expr,expr)>
<!ELEMENT div    (expr,expr)>
<!ELEMENT NUMBER (#PCDATA)>
<!ELEMENT ID     (#PCDATA)>

=== jfcmacro/wb-jfcmacro-java/xml/expr/ExprFail1.xml
<?xml version="1.1" encoding="ISO-8859-1"?>
<!DOCTYPE expr SYSTEM "expr.dtd">
<expr>
  <add>
    <expr>
      <ID>
	var1
      </ID>
    </expr>
    <expr>
      <add>
	<expr>
	  <ID>
	    var1
	  </ID>
	</expr>
      </add>
    </expr>
  </add>
</expr>

=== jfcmacro/wb-jfcmacro-java/xml/expr/ExprOKVal.xml
<?xml version="1.1" encoding="ISO-8859-1"?>
<!DOCTYPE expr SYSTEM "expr.dtd">
<expr>
  <add>
    <expr>
      <NUMBER>
	3
      </NUMBER>
    </expr>
    <expr>
      <mult>
	<expr>
	  <NUMBER>
	    3
	  </NUMBER>
	</expr>
	<expr>
	  <NUMBER>
	    4
	  </NUMBER>
	</expr>
      </mult>
    </expr>
  </add>
</expr>
