=== jfcmacro/wb-jfcmacro-java/xml/BienFormado/Maquina.dtd
<!ELEMENT Maquina (AlfabetoEntrada,
 AlfabetoSalida,
 Estados,
 FuncionesEstado,
 FuncionesSalida)>
<!ELEMENT AlfabetoEntrada (Simbolo*)>
<!ELEMENT AlfabetoSalida (Simbolo*)>
<!ELEMENT Estados (Estado*)>
<!ELEMENT FuncionesEstado (FuncionEstado*)>
<!ELEMENT FuncionesSalida (FuncionSalida*)>
<!ELEMENT Simbolo (#PCDATA)>
<!ELEMENT Estado (#PCDATA)>
<!ELEMENT FuncionEstado (Simbolo, Estado, Estado)>
<!ELEMENT FuncionSalida (Simbolo, Estado, Simbolo)>
<!ATTLIST Maquina EstadoInicial CDATA #REQUIRED>

=== jfcmacro/wb-jfcmacro-java/xml/jaxp/Maquina.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Maquina SYSTEM "file:./Maquina.dtd">
<Maquina EstadoInicial="E1">
  <AlfabetoEntrada>
    <Simbolo>A</Simbolo>
    <Simbolo>B</Simbolo>
    <Simbolo>C</Simbolo>
  </AlfabetoEntrada>
  <AlfabetoSalida>
    <Simbolo>A</Simbolo>
    <Simbolo>B</Simbolo>
    <Simbolo>C</Simbolo>
  </AlfabetoSalida>
  <Estados>
    <Estado>X</Estado>
    <Estado>Y</Estado>
  </Estados>
  <FuncionesEstado>
    <FuncionEstado>
      <Simbolo>A</Simbolo>
      <Estado>X</Estado>
      <Estado>X</Estado>
    </FuncionEstado>
  </FuncionesEstado>
  <FuncionesSalida>
    <FuncionSalida>
      <Simbolo>A</Simbolo>
      <Estado>X</Estado>
      <Simbolo>A</Simbolo>
    </FuncionSalida>
  </FuncionesSalida>
</Maquina>

=== jfcmacro/wb-jfcmacro-java/xml/BienFormado/Maquina.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Maquina SYSTEM "Maquina.dtd">
<Maquina EstadoInicial="E1">
  <AlfabetoEntrada>
    <Simbolo>A</Simbolo>
    <Simbolo>B</Simbolo>
    <Simbolo>C</Simbolo>
  </AlfabetoEntrada>
  <AlfabetoSalida>
    <Simbolo>A</Simbolo>
    <Simbolo>B</Simbolo>
    <Simbolo>C</Simbolo>
  </AlfabetoSalida>
  <Estados>
    <Estado>X</Estado>
    <Estado>Y</Estado>
  </Estados>
  <FuncionesEstado>
    <FuncionEstado>
      <Simbolo>A</Simbolo>
      <Estado>X</Estado>
      <Estado>X</Estado>
    </FuncionEstado>
    <FuncionEstado>
      <Simbolo>B</Simbolo>
      <Estado>X</Estado>
      <Estado>Y</Estado>
    </FuncionEstado>
    <FuncionEstado>
      <Simbolo>B</Simbolo>
      <Estado>Y</Estado>
      <Estado>Y</Estado>
    </FuncionEstado>
    <FuncionEstado>
      <Simbolo>C</Simbolo>
      <Estado>Y</Estado>
      <Estado>X</Estado>
    </FuncionEstado>
  </FuncionesEstado>
  <FuncionesSalida>
    <FuncionSalida>
      <Simbolo>A</Simbolo>
      <Estado>X</Estado>
      <Simbolo>A</Simbolo>
    </FuncionSalida>
  </FuncionesSalida>
</Maquina>
