=== jfcmacro/wb-jfcmacro-java/xml/BienFormado/ordenes-libros.dtd
<!-- Un ejemplo para comprobar como hacer un ejemplo de libros -->
<!ELEMENT ordenes-libros (cliente, tienda, bienes)*>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT tienda (#PCDATA)>
<!ELEMENT bienes (libros|revistas)*>
<!ELEMENT libros (nombre)*>
<!ELEMENT revistas (nombre)*>
<!ELEMENT nombre (#PCDATA)>

=== jfcmacro/wb-jfcmacro-java/xml/BienFormado/ordenes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ordenes-libros SYSTEM "ordenes-libros.dtd">
<ordenes-libros>
<cliente>Duckman</cliente>
<tienda>Libreria el mal libro</tienda>
<bienes>
<libros>
<nombre>Como tumbar a su mejor amigo</nombre>
</libros>
<revistas>
<nombre>Playboy</nombre>
<nombre>Penthouse</nombre>
</revistas>
</bienes>
<cliente>Corflake</cliente>
<tienda>Libreria el buen libro</tienda>
<bienes>
<libros>
<nombre>Como ayudar a su tumbador amigo</nombre>
</libros>
</bienes>
</ordenes-libros>
